### PR TITLE
feat(movedEvent): emit 'moved' on drag ended

### LINKED ISSUE #17: Moved event behaves the same as 'move' event
It looks like 'moved' and 'move' events are fired at the same time, which means it cannot be used to set the state of the current datapoints.

I would think 'moved' would be triggered after you have released the mouse button again, so the new data points can be saved in a database.

### PR DESCRIPTION
**Pull request by andersfibiger**
resolves #17 

Fires the 'moved' event when dragging has ended.

### CODE REVIEW

**Review by nagi1 — APPROVED** [review]
Wonderful, Thanks for your time.

**Comment by andersfibiger** [comment]
No problem :) Are you creating an update version of the package? :)

**Comment by nagi1** [comment]
Yup, I'll publish a new version now

**Comment by nagi1** [comment]
You can upgrade now, Thank you for taking the time to fix I really
appreciate it.

Cheers :)

**Comment by andersfibiger** [comment]
Great, thanks! It works on my end :)

Cheers! :)

**Pull request merged**
